spring:
  application:
    name: test
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # session 30 天过期
  session:
    store-type: redis
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://149.88.92.184:3306/test1
    username: test1
    password: AdWJhxcrpr2pNNM5
server:
  address: 0.0.0.0
  port: 8010
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
  tomcat:
    redirect-context-root: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）